name: "release-tag"

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  tagged-release:
      runs-on: ubuntu-latest
      name: release
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: build windows amd64
          run: GOOS=windows GOARCH=amd64 go build -o benchtool-go-win-x64.exe cmd/benchtool-go/main.go
        - name: build windows i386
          run: GOOS=windows GOARCH=386 go build -o benchtool-go-win.exe cmd/benchtool-go/main.go
        - name: build linux amd64
          run: GOOS=linux GOARCH=amd64 go build -o benchtool-go-linux-x64 cmd/benchtool-go/main.go
        - name: build linux i386
          run: GOOS=linux GOARCH=386 go build -o benchtool-go-linux cmd/benchtool-go/main.go
        - name: build linux arm
          run: GOOS=linux GOARCH=arm go build -o benchtool-go-linux-arm cmd/benchtool-go/main.go
        - name: build linux arm64
          run: GOOS=linux GOARCH=arm64 go build -o benchtool-go-linux-arm64 cmd/benchtool-go/main.go
        - name: build mac amd64
          run: GOOS=darwin GOARCH=amd64 go build -o benchtool-go-mac-amd64 cmd/benchtool-go/main.go
        - name: build mac arm64
          run: GOOS=darwin GOARCH=arm64 go build -o benchtool-go-mac-arm64 cmd/benchtool-go/main.go
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              benchtool-go-*